export const GAME_NAME: Readonly<string> = 'Type War';
export const REPO_URL: Readonly<string> = 'https://github.com/guimorone/projeto-jogos';
export const MAX_LEVEL: Readonly<number> = 5;
export const DELAY_TO_START_NEW_LEVEL_MS: Readonly<number> = 3000; // ms
export const INITIAL_PLAYER_HEALTH: Readonly<number> = 10;
export const INITIAL_MIN_WORDS_LENGTH: Readonly<number> = 3;
export const INITIAL_MAX_WORDS_LENGTH: Readonly<number> = 5;
export const INITIAL_TOTAL_WAVES: Readonly<number> = 2;
export const INITIAL_WAVE_DELAY: Readonly<number> = 15000; // ms
export const INITIAL_COUNT_WORDS_IN_WAVE: Readonly<number> = 3;
export const INITIAL_WORDS_SPEED: Readonly<number> = 12500; // ms
